using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SE.Neo.Core.Migrations
{
    public partial class InsertRecordsInRegionScaleForNationalLevel : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Insert into [dbo].[Region_Scale_Initiative] ([CMS_Region_Id], [Scale_Id], [Created_Ts], [Last_Change_Ts])" +
                                "Values(" +
                                "(Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Nigeria'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Egypt'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Senegal'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Uganda'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Algeria'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Angola'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Botswana'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Burkina Faso'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Burundi'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Cameroon'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Central African Republic'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Chad'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Congo'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Côte d''Ivoire'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Democratic Republic of the Congo'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Djibouti'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Equatorial Guinea'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Eritrea'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Ethiopia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Gabon'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Gambia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Ghana'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Guinea'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Guinea-Bissau'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Kenya'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Lesotho'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Liberia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Libya'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Madagascar'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Malawi'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Mali'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Mauritania'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Mauritius'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Morocco'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Mozambique'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Namibia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Niger'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Rwanda'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Sierra Leone'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Somalia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'South Africa'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'South Sudan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Sudan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Swaziland'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Tanzania'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Togo'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Tunisia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Western Sahara'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Zambia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Zimbabwe'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'China'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Japan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Afghanistan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Azerbaijan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Bahrain'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Bangladesh'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Bhutan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Cambodia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Hong Kong'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'India'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Indonesia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Iran'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Iraq'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Israel'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Jordan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Kazakhstan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Kuwait'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Kyrgyzstan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Laos'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Lebanon'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Malaysia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Maldives'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Mongolia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Myanmar'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Nepal'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'New Caledonia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'North Korea'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Oman'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Pakistan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Philippines'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Qatar'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Saudi Arabia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Singapore'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'South Korea'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Sri Lanka'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Svalbard and Jan Mayen Islands'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Syria'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Taiwan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Tajikistan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Thailand'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Timor-Leste'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Turkmenistan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'United Arab Emirates'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Uzbekistan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Vietnam'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Yemen'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Ukraine'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Poland'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'France'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'United Kingdom'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Albania'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Armenia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Austria'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Belarus'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Belgium'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Benin'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Bosnia and Herzegovina'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Bulgaria'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Croatia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Cyprus'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Czech Republic'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Denmark'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Estonia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Finland'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Georgia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Germany'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Greece'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Greenland'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Hungary'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Iceland'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Ireland'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Italy'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Latvia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Liechtenstein'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Lithuania'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Luxembourg'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Macedonia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Moldova'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Monaco'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Montenegro'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Netherlands'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Norway'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Portugal'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Romania'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Russia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Serbia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Slovakia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Slovenia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Spain'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Sweden'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Switzerland'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Turkey'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Mexico'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Guatemala'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Honduras'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Anguilla'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Antigua and Barbuda'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Barbados'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Belize'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Cayman Islands'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Costa Rica'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Cuba'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Curaçao'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Dominica'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Dominican Republic'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'El Salvador'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Grenada'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Guadeloupe'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Haiti'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Jamaica'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Martinique'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Montserrat'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Nicaragua'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Panama'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Saint Kitts and Nevis'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Saint Martin, FR'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Saint Vincent and the Grenadines'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Trinidad and Tobago'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Australia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Fiji'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'New Zealand'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Papua New Guinea'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Solomon Islands'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Vanuatu'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Brazil'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Argentina'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Ecuador'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Bolivia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Chile'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Colombia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'French Guiana'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Guyana'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Paraguay'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Peru'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Suriname'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Uruguay'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='National (Choose one or more countries)'),GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Venezuela'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - All'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())," +
                                "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Canada'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)'), GETDATE(), GETDATE())"
                                );
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Delete from [dbo].[Region_Scale_Initiative] where Scale_Id = (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'National (Choose one or more countries)')");
        }
    }
}
