using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SE.Neo.Core.Migrations
{
    public partial class InsertRecordsIntoInitiativeSubSteps : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Insert into [dbo].[Initiative_Sub_Step] ( [Initiative_Step_Id] , [Category_Id] , [Title], [Sub_Step_Order] , [Created_Ts] , [Last_Change_Ts] ) Values " +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Determine your company''s primary motivations for pursuing onsite solar. Consider sustainability goals, cost reduction, risk management, and resiliency, among others.', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Identify site(s). Use the Zeigo Network DER Map to determine viability based on available incentives, policies, and solar resource. Also consider site ownership, roof age and available space, and long term site plans.', 2 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Review Zeigo Network Learn content to grasp the basics regarding contract structures, risks, process steps, and keys to success.', 3 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'For identified sites, gather 12 months of hourly interval data, a recent utility invoice, any applicable retail supply contracts and invoices, as well as site one-line diagrams.', 4 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Introduce the project to key members of other departments such as procurement, facilities/real estate, sustainability, and finance. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Highlight internal requirements and non-starters. Examples include CAPEX vs. PPA structure, roof replacements, term length limits, ROI expectations, and plans for facility divestment. ', 2 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Determine if an RFP is required or if sole sourcing is acceptable.', 3 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Identify an Internal Champion who can see the project through to completion. ', 4 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'If desired, request an \"indicative proposal\" from a single developer to better understand the potential for the chosen site(s). ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Request formal proposals from one or more developers, including specific requirements and expectations to ensure standard responses. ', 2 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Provide billing data, site data, and invoices to all participating developers. Provide a point of contact for those desiring to do a site-walk.', 3 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Ensure all proposals adhere to stated requirements. Respond to any questions posed and clarify any needed points for all developers. ', 4 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Schedule time for each participating developer to present their proposal and answer questions. ', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Perform a \"like to like\" comparison of offers received and rank proposals according to primarily goals. ', 2 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Choose and notify your preferred partner. Sign a Letter of Intent (LOI) to enable the developer to proceed with next steps. ', 3 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'If the site has an existing retail supply contract, ensure there is no conflict with the proposed solar system. ', 4 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Receive and review final proposal from chosen developer. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Review and negotiate commercial terms with legal counsel.', 2 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Re-engage stakeholders identified in step 2 to confirm alignment before proceeding.', 3 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Sign the contract!', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Create a communications plan for announcing the project. ', 2 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Prepare plans for project execution per timeline provided by developer.', 3 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Onsite Solar'), 'Ensure ongoing financial and operational evaluation is in place prior to go-live date.', 4 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Determine your company''s primary motivations for pursuing battery storage. Consider sustainability goals, cost reduction, risk management, and resiliency, among others.', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Identify site(s). Use the Zeigo Network DER Map to determine viability based on available incentives, policies, and solar resource. Also consider site ownership, roof age and available space, and long term site plans.', 2 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Review Zeigo Network Learn content to grasp the basics regarding contract structures, risks, process steps, and keys to success.', 3 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'For identified sites, gather 12 months of hourly interval data, a recent utility invoice, any applicable retail supply contracts and invoices, as well as site one-line diagrams. ', 4 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Introduce the project to key members of other departments such as procurement, facilities/real estate, sustainability, and finance. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Highlight internal requirements and non-starters. Examples include CAPEX vs. PPA structure, roof replacements, term length limits, ROI expectations, and facility divestment. ', 2 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Determine if an RFP is required or if sole sourcing is acceptable.', 3 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Identify an Internal Champion who can see the project through to completion. ', 4 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'If desired, request an \"indicative proposal\" from a single developer to better understand the potential for the chosen site(s). ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Request formal proposals from one or more developers, including specific requirements and expectations to ensure standard responses. ', 2 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Provide billing data, site data, and invoices to all participating developers. Provide a point of contact for those desiring to do a site-walk.', 3 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Ensure all proposals adhere to stated requirements. Respond to any questions posed and clarify any needed points for all developers. ', 4 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Schedule time for each participating developer to present their proposal and answer questions. ', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Perform a \"like to like\" comparison of offers received and rank proposals according to primarily goals. ', 2 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Choose and notify your preferred partner. Sign a Letter of Intent (LOI) to enable the developer to proceed with next steps. ', 3 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'If the site has an existing retail supply contract, ensure there is no conflict with the proposed solar system. ', 4 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Receive and review final proposal from chosen developer. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Review and negotiate commercial terms with legal counsel.', 2 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Re-engage stakeholders identified in step 2 to confirm alignment before proceeding.', 3 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Sign the contract!', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Create a communications plan for announcing the project. ', 2 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Prepare plans for project execution per timeline provided by developer.', 3 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Battery Storage'), 'Ensure ongoing financial and operational evaluation is in place prior to go-live date.', 4 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Determine your company''s primary motivations for pursuing community solar. Consider sustainability goals, cost reduction, community involvement, and others. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Review Zeigo Network Learn content to grasp the basics and ensure a solid understanding of the structure.', 2 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Identify preliminary site(s) in view. This can be refined once a developer and projects are identified.', 3 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'For identified sites, gather a recent utility invoice, any applicable retail supply contracts and invoices, and expected annual KWh usage for the next 20 years.', 4 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Introduce the project to key members of other departments such as procurement,  sustainability, and finance. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Determine if an RFP is required or if sole sourcing is acceptable.', 2 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Identify an Internal Champion who can see the project through to completion. ', 3 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'If desired, request an \"indicative proposal\" from a single developer to better understand the potential for the chosen site(s). ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Request formal proposals from one or more developers, including specific requirements and expectations to ensure standard responses. ', 2 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Provide billing data, site data, and invoices to all participating developers. ', 3 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Schedule time for each participating developer to present their proposal and answer questions. ', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Perform a \"like to like\" comparison of offers received and rank proposals according to primarily goals. ', 2 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Choose and notify your preferred partner. ', 3 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'If the site has an existing retail supply contract, ensure there is no conflict with the proposed community solar contract.', 4 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Receive and review final proposal from chosen developer.  ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Review and negotiate terms with legal counsel.', 2 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Re-engage stakeholders identified in step 2 to confirm alignment before proceeding.', 3 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Sign the contract!', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Community Solar'), 'Create a communications plan for announcing the project. ', 2 , GETDATE(), GETDATE());");

            migrationBuilder.Sql("Insert into [dbo].[Initiative_Sub_Step] ( [Initiative_Step_Id] , [Category_Id] , [Title], [Content], [Sub_Step_Order] , [Created_Ts] , [Last_Change_Ts] ) Values" +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Aggregated PPAs'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Aggregated PPAs'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Aggregated PPAs'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Aggregated PPAs'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Aggregated PPAs'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Aggregated PPAs'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Carbon Offset Purchasing'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Carbon Offset Purchasing'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Carbon Offset Purchasing'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Carbon Offset Purchasing'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Carbon Offset Purchasing'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Carbon Offset Purchasing'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='EAC Purchasing'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='EAC Purchasing'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='EAC Purchasing'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='EAC Purchasing'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='EAC Purchasing'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='EAC Purchasing'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Audits & Consulting'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Audits & Consulting'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Audits & Consulting'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Audits & Consulting'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Audits & Consulting'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Audits & Consulting'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Equipment Measures'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Equipment Measures'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Equipment Measures'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Equipment Measures'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Equipment Measures'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Efficiency Equipment Measures'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Emerging Technologies'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Emerging Technologies'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Emerging Technologies'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Emerging Technologies'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Emerging Technologies'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Emerging Technologies'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='EV Charging & Fleet Electrification'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='EV Charging & Fleet Electrification'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='EV Charging & Fleet Electrification'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='EV Charging & Fleet Electrification'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='EV Charging & Fleet Electrification'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='EV Charging & Fleet Electrification'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Fuel Cells'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Fuel Cells'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Fuel Cells'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Fuel Cells'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Fuel Cells'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Fuel Cells'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Offsite Power Purchase Agreement'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Offsite Power Purchase Agreement'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Offsite Power Purchase Agreement'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Offsite Power Purchase Agreement'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Offsite Power Purchase Agreement'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Offsite Power Purchase Agreement'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Renewable Retail Electricity'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Renewable Retail Electricity'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Renewable Retail Electricity'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Renewable Retail Electricity'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Renewable Retail Electricity'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Renewable Retail Electricity'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE())," +
                "( 1 , (select CMS_Category_Id from CMS_Category where Category_Name ='Utility Green Tariff'), '', 'The most important component of this step is to gain clarity on your motivation and objective. Use Zeigo Network Learn content to better understand the value of the solution. From there, collect data that will inform the available options and next steps. ', 1 , GETDATE(), GETDATE())," +
                "( 2 , (select CMS_Category_Id from CMS_Category where Category_Name ='Utility Green Tariff'), '', 'Most decarbonization procurement initiatives will require diverse stakeholders'' approval. Identify these individuals and groups and engage with them early. Identify a project champion to move things forward. ', 1 , GETDATE(), GETDATE())," +
                "( 3 , (select CMS_Category_Id from CMS_Category where Category_Name ='Utility Green Tariff'), '', 'Not every initiative will require offers from multiple providers. Get clarity on your company''s requirements. Then identify the provider or providers to engage. Again, the Zeigo Network can help here. Ensure you provide detailed information and requirements as well as your objectives for the initiative.', 1 , GETDATE(), GETDATE())," +
                "( 4 , (select CMS_Category_Id from CMS_Category where Category_Name ='Utility Green Tariff'), '', 'For a larger initiative, it''s a good practice to give providers the opportunity to present their offers. For smaller ones it can be a simple comparison exercise - against other offers and/or stated expectations. Choose the provider and offer that best meets your needs. ', 1 , GETDATE(), GETDATE())," +
                "( 5 , (select CMS_Category_Id from CMS_Category where Category_Name ='Utility Green Tariff'), '', 'At this point, the stakeholders from step 2 may need to be reengaged and a legal review will likely be required. Balance care and patience with an awareness of the danger of moving too slowly.', 1 , GETDATE(), GETDATE())," +
                "( 6 , (select CMS_Category_Id from CMS_Category where Category_Name ='Utility Green Tariff'), '', 'Executing the contracting is exciting! It''s also only the beginning. A communications plan must next be considered. Any reporting implications and ongoing operational management must quickly be planned as well. ', 1 , GETDATE(), GETDATE());");

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Delete from [dbo].[Initiative_Sub_Step]");
        }
    }
}
