using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SE.Neo.Core.Migrations
{
    public partial class InsertRecordsInRegionScaleForStateLevel : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Insert into [dbo].[Region_Scale_Initiative] ([CMS_Region_Id], [Scale_Id], [Created_Ts], [Last_Change_Ts])" +
                                 "Values(" +
                                 "(Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Alabama'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Alaska'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Arizona'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Arkansas'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Colorado'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - California'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Bahamas'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Puerto Rico'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Turks and Caicos Islands'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Virgin Islands, British'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'Virgin Islands, U.S.'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Connecticut'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - D.C.'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Delaware'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Florida'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Georgia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Hawaii'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Idaho'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Illinois'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Indiana'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Iowa'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Kansas'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Kentucky'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Louisiana'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Maine'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Maryland'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Massachusetts'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Michigan'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Minnesota'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Mississippi'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Missouri'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Montana'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Nebraska'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Nevada'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - New Hampshire'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - New Jersey'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - New Mexico'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - New York'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - North Carolina'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - North Dakota'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Ohio'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Oklahoma'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Oregon'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Pennsylvania'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Rhode Island'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - South Carolina'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - South Dakota'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Tennessee'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Texas'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Utah'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Vermont'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Virginia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Washington'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - West Virginia'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Wisconsin'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())," +
                                 "((Select CMS_Region_Id from [dbo].[CMS_Region] where Region_Name = 'US - Wyoming'), (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name='State Level (Choose one or more states - US only)'),GETDATE(), GETDATE())"
                                 );
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Delete from [dbo].[Region_Scale_Initiative] where Scale_Id = (Select Initiative_Scale_Id from [dbo].[Initiative_Scale] where Name = 'State Level (Choose one or more states - US only)')");
        }
    }
}
