import { TagInterface } from '../../../core/interfaces/tag.interface';

export const SETTLEMENT_HUB_LIST: TagInterface[] = [
  { name: 'None', id: null, sort: 0 },
  { name: 'AZ-PV', id: 1, sort: 1 },
  { name: 'CA-NP15', id: 2, sort: 2 },
  { name: 'CA-SP15', id: 3, sort: 3 },
  { name: 'CA-ZP26', id: 4, sort: 4 },
  { name: 'ComEd Load Zone', id: 36, sort: 5 },
  { name: 'Dominion Load Zone', id: 37, sort: 6 },
  { name: 'ERCOT-H', id: 5, sort: 7 },
  { name: 'ERCOT-N', id: 6, sort: 8 },
  { name: 'ERCOT-S', id: 7, sort: 9 },
  { name: 'ERCOT-W', id: 8, sort: 10 },
  { name: 'MISO-Ark', id: 10, sort: 11 },
  { name: 'MISO-Gul', id: 11, sort: 12 },
  { name: 'MISO-IA', id: 9, sort: 13 },
  { name: 'MISO-IL', id: 12, sort: 14 },
  { name: 'MISO-IN', id: 13, sort: 15 },
  { name: 'MISO-LA', id: 45, sort: 16 },
  { name: 'MISO-MI', id: 14, sort: 17 },
  { name: 'MISO-MN', id: 15, sort: 18 },
  { name: 'MISO-MO', id: 16, sort: 19 },
  { name: 'MISO-ND', id: 17, sort: 20 },
  { name: 'NE-CT', id: 39, sort: 21 },
  { name: 'NE-MA', id: 40, sort: 22 },
  { name: 'NE-ME', id: 41, sort: 23 },
  { name: 'NE-NH', id: 42, sort: 24 },
  { name: 'NE-RI', id: 43, sort: 25 },
  { name: 'NEPOOL', id: 38, sort: 26 },
  { name: 'NY-A', id: 18, sort: 27 },
  { name: 'NY-G', id: 19, sort: 28 },
  { name: 'NY-J', id: 20, sort: 29 },
  { name: 'PJM-AEP GEN HUB', id: 23, sort: 30 },
  { name: 'PJM-AEP-DAYTON HUB', id: 24, sort: 31 },
  { name: 'PJM-ATSI GEN HUB', id: 25, sort: 32 },
  { name: 'PJM-CHICAGO GEN HUB', id: 26, sort: 33 },
  { name: 'PJM-CHICAGO HUB', id: 27, sort: 34 },
  { name: 'PJM-DOMINION HUB', id: 28, sort: 35 },
  { name: 'PJM-EASTERN HUB', id: 29, sort: 36 },
  { name: 'PJM-N ILLINOIS HUB', id: 30, sort: 37 },
  { name: 'PJM-N NEW JERSEY HUB', id: 31, sort: 38 },
  { name: 'PJM-N OHIO HUB', id: 32, sort: 39 },
  { name: 'PJM-N WEST INT HUB', id: 33, sort: 40 },
  { name: 'PJM-N WESTERN HUB', id: 34, sort: 41},
  { name: 'PSEG Load Zone', id: 35, sort: 42 },
  { name: 'SPP-N', id: 22, sort: 43 },
  { name: 'SPP-S', id: 21, sort: 44 },

  { name: 'Other', id: 44, sort: 45 },
];
