export enum PermissionTypeEnum {
  AdminAll = 1,
  AnnouncementManagement = 2,
  CompanyManagement = 3,
  DataSync = 4,
  EventManagement = 5,
  MessagesAll = 6,
  ProjectCatalogView = 7,
  ProjectsManageAll = 8,
  ProjectsManageOwn = 9,
  SendQuote = 10,
  ToolManagement = 11,
  ForumManagement = 12,
  UserAccessManagement = 13,
  UserProfileEdit = 14,
  EmailAlertManagement = 15,
  ProjectPrivateDetailsView = 16,
  ManageCompanyUsers = 17,
  ManageOwnCompany = 18,
  ManageCompanyProjects = 19,
  ViewCompanyMessages = 20,
  InitiativeManageOwn = 21,
  InitiativeManageAll = 22,
  TierManagement = 23
}
